apiVersion: apps/v1
kind: Deployment
metadata:
  name: care-django-production

spec:
  selector:
    matchLabels:
      app: care-django-production

  template:
    metadata:
      labels:
        name: care-django-production
        app: care-django-production
        env: production
        namespace: default
    spec:
      # imagePullSecrets:
      #   - name: githubreg
      containers:
        - name: care
          image: ghcr.io/ohcnetwork/care:production-latest
          imagePullPolicy: Always
          command: ["/bin/bash", "-c", "--"]
          args: ["/app/start.sh"]
          ports:
            - name: django
              containerPort: 9000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: care-production
            - secretRef:
                name: care-production
          env:
            - name: RESTART_
              value: "20200331015742"
            - name: deployment-version
              value: "_BUILD_NUMBER_"
          # resources:
          #   requests:
          #     memory: "200Mi"
          #     cpu: "200m"
          #   limits:
          #     memory: "300Mi"
          #     cpu: "200m"
      #     volumeMounts:
      #       - name: newrelic-ini
      #         mountPath: /etc/newrelic.ini
      #         subPath: newrelic.ini
      #         readOnly: true
      # volumes:
      #   - name: newrelic-ini
      #     secret:
      #       secretName: care-production
      #       defaultMode: 0444
      #       items:
      #         - key: NEWRELIC_INI
      #           path: newrelic.ini
