apiVersion: apps/v1
kind: Deployment
metadata:
  name: care-fe-production-deployment

spec:
  selector:
    matchLabels:
      app: care-fe-production

  template:
    metadata:
      labels:
        app: care-fe-production
    spec:
      containers:
        - name: care-fe
          image: ghcr.io/ohcnetwork/care_fe:production-latest
          imagePullPolicy: Always
          env:
            - name: deployment-version
              value: "_BUILD_NUMBER_"
          ports:
            - name: care-fe-prod
              containerPort: 80
              protocol: TCP
          # resources:
          #   requests:
          #     memory: "200Mi"
          #     cpu: "100m"
          #   limits:
          #     memory: "300Mi"
          #     cpu: "100m"
          volumeMounts:
            - name: care-fe-production
              mountPath: /usr/share/nginx/html/config.json
              subPath: config.json
      volumes:
        - name: care-fe-production
          configMap:
            name: care-fe-production
            items:
              - key: config.json
                path: config.json
