apiVersion: apps/v1
kind: Deployment
metadata:
  name: care-django-production
spec:
  template:
    metadata:
      labels:
        name: care-django-production
        app: care-django-production
        env: production
        namespace: default
    spec:
      containers:
        - name: care
          image: ghcr.io/coronasafe/care:production-latest
          imagePullPolicy: Always
          resources:
           requests:
             memory: "200Mi"
             cpu: "200m"
           limits:
             memory: "300Mi"
             cpu: "200m"
          command:
            - /start
          ports:
            - containerPort: 9000
              name: django
              protocol: TCP
          envFrom:
            - configMapRef:
                name: care-production
            - secretRef:
                name: care-production
          env:
            - name: RESTART_
              value: "20200331015742"
            - name: deployment-version
              value: "_BUILD_NUMBER_"
          volumeMounts:
            - name: newrelic-ini
              mountPath: /etc/newrelic.ini
              subPath: newrelic.ini
              readOnly: true
      volumes:
        - name: newrelic-ini
          secret:
            secretName: care-production
            defaultMode: 0444
            items:
              - key: NEWRELIC_INI
                path: newrelic.ini
  selector:
    matchLabels:
      app: care-django-production

