apiVersion: apps/v1
kind: Deployment
metadata:
  name: fidelius
spec:
  template:
    metadata:
      labels:
        name: fidelius
        app: fidelius
        env: production
    spec:
      containers:
        - name: fidelius
          image: khavinshankar/fidelius:amd64
          imagePullPolicy: Always
          # resources:
          #   requests:
          #     memory: "1Gi"
          #     cpu: "250m"
          #   limits:
          #     memory: "2Gi"
          #     cpu: "500m"
          ports:
            - containerPort: 8090
              name: fidelius
              protocol: TCP
  selector:
    matchLabels:
      app: fidelius