apiVersion: apps/v1
kind: Deployment
metadata:
  name: care-nginx-production

spec:
  selector:
    matchLabels:
      app: care-nginx-production

  template:
    metadata:
      labels:
        app: care-nginx-production
    spec:
      containers:
        - name: nginx
          image: nginx:1.26
          # resources:
          #   requests:
          #     cpu: "100m"
          #     memory: "200Mi"
          #   limits:
          #     cpu: "100m"
          #     memory: "400Mi"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-conf-production
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-conf-production
          configMap:
            name: nginx-conf-production
            items:
              - key: nginx.conf
                path: nginx.conf
