apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cache-production
  labels:
    app: redis-cache-production

spec:
  selector:
    matchLabels:
      app: redis-cache-production
  replicas: 1

  template:
    metadata:
      labels:
        app: redis-cache-production
    spec:
      containers:
        - name: redis
          image: redis/redis-stack-server:6.2.6-v17
          # resources:
          #   requests:
          #     cpu: "100m"
          #     memory: "100Mi"
          #   limits:
          #     cpu: "100m"
          #     memory: "400Mi"
          ports:
            - containerPort: 6379
