apiVersion: v1
kind: Service
metadata:
  name: fidelius
  labels:
    app: fidelius
    env: production
spec:
  ports:
    - port: 80
      targetPort: 8090
      protocol: TCP
  type: ClusterIP
  selector:
    app: fidelius