apiVersion: v1
kind: Service
metadata:
  name: metabase
  labels:
    app: metabase
    env: production

spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  type: ClusterIP
  selector:
    app: metabase
