apiVersion: v1
kind: Service
metadata:
  name: care-nginx-production
  labels:
    app: care-nginx-production
    env: production
    namespace: default
spec:
  type: NodePort
  ports:
    - port: 80
      name: https
      targetPort: 80
      protocol: TCP
  selector:
    app: care-nginx-production
