apiVersion: v1
kind: Secret
metadata:
  name: care-production
  labels:
    app: care
    env: production
    namespace: default
type: Opaque
stringData:
  NEWRELIC_INI: "" #newrelic ini
  DJANGO_SECRET_KEY: "" #django secret key
  NEW_RELIC_ENVIRONMENT: "" #newrelic env name
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  POSTGRES_PASSWORD: "" #care db password
  CELERY_BROKER_URL: "redis://:@redis-cache-production:6379/0"
  REDIS_URL: "redis://:@redis-cache-production:6379/0"
  DJANGO_ADMIN_URL: "" #django admin page slug
  POSTGIS_URL: "postgres://postgres:postgres_password@hostname:5432/care"
  CURRENT_DOMAIN: "https://care.demo.example.in"
  EMAIL_HOST: "" #email server host
  EMAIL_USER: "" #email server user
  EMAIL_PASSWORD: "" #email server password
  SENTRY_DSN: "" #sentry dsn
  SNS_ACCESS_KEY: ""
  SNS_SECRET_KEY: ""
  FILE_UPLOAD_BUCKET: "care-patient-data" #bucket name for patient-data
  FILE_UPLOAD_KEY: "" #HMAC key
  FILE_UPLOAD_SECRET: "" #HMAC secret
  AUDIT_LOG_ENABLED: "1"
  GOOGLE_RECAPTCHA_SITE_KEY: '6Le3Io8fAAAAACG99dsQue4k670N4RduaxniFCUa'
  GOOGLE_RECAPTCHA_SECRET_KEY: '6Le3Io8fAAAAAOyR3ynonXTCE-lApmuTrzQQoUdN'
  VAPID_PUBLIC_KEY: "" #Vapid public key
  VAPID_PRIVATE_KEY: "" #Vapid private key
  FACILITY_S3_BUCKET: "care-facility" #bucket name for facility
  FACILITY_S3_KEY: "" #HMAC key
  FACILITY_S3_SECRET: "" #HMAC secret
  FACILITY_S3_BUCKET_ENDPOINT: "https://storage.cloud.google.com/care-facility"
  FACILITY_S3_STATIC_PREFIX: "https://storage.cloud.google.com/care-facility"